name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++ libboost-dev
      
      - name: Configure CMake
        run: cmake -B build
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Package
        run: |
          mkdir -p release
          cp build/my_program release/
          tar -czvf release/my_program-linux.tar.gz -C release my_program
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_program-linux
          path: release/my_program-linux.tar.gz
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/my_program-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: brew install cmake boost
      
      - name: Configure CMake
        run: cmake -B build
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Package
        run: |
          mkdir -p release
          cp build/my_program release/
          tar -czvf release/my_program-macos.tar.gz -C release my_program
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_program-macos
          path: release/my_program-macos.tar.gz
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/my_program-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
