name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++ libboost-dev libboost-filesystem-dev libboost-program-options-dev

      - name: Clean previous CMake cache
        run: rm -rf build

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir -p release
          cp build/lab7 release/
          tar -czvf release/lab7-linux.tar.gz -C release lab7

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab7-linux
          path: release/lab7-linux.tar.gz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/lab7-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake boost

      - name: Clean previous CMake cache
        run: rm -rf build

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir -p release
          cp build/lab7 release/
          tar -czvf release/lab7-macos.tar.gz -C release lab7

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab7-macos
          path: release/lab7-macos.tar.gz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/lab7-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}