name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cpp: [17] # Указываем версию C++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Boost on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev g++

    - name: Set up Boost and LLVM on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install boost llvm
        echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV

    - name: Compile the code on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        g++ -std=c++${{ matrix.cpp }} -o main main.cpp -lboost_system -lboost_filesystem

    - name: Compile the code on macOS
      if: matrix.os == 'macos-latest'
      run: |
        $CXX -std=c++${{ matrix.cpp }} -o main main.cpp -L$(brew --prefix boost)/lib -I$(brew --prefix boost)/include -lboost_system -lboost_filesystem

    - name: Run the program
      run: |
        ./main